#ifndef PHOTOION_CODATA2022_H
#define PHOTOION_CODATA2022_H

/* CODATA 2022 recommended values, SI units, as printed by NIST.
 *
 * GENERATED by photoion_codata_gen.py -- do not edit by hand.
 * Source: NIST "Fundamental Physical Constants --- Complete Listing",
 *   2022 CODATA adjustment
 *   sha256 77fb90e66c40db3e6eb16630bc9c88e4c7c8beddbe5e71be406f2f26e3f67e67
 * photoion_const.h derives the cgs values the models use from these. */

#define CODATA_SPEED_OF_LIGHT            (299792458.)
    /* speed of light in vacuum [m s^-1], exact */
#define CODATA_PLANCK                    (6.62607015e-34)
    /* Planck constant [J Hz^-1], exact */
#define CODATA_ELECTRON_VOLT             (1.602176634e-19)
    /* electron volt [J], exact */
#define CODATA_BOHR_RADIUS               (5.29177210544e-11)
    /* Bohr radius [m], uncertainty 0.00000000082e-11 */
#define CODATA_CLASSICAL_ELECTRON_RADIUS (2.8179403205e-15)
    /* classical electron radius [m], uncertainty 0.0000000013e-15 */
#define CODATA_THOMSON_CROSS_SECTION     (6.6524587051e-29)
    /* Thomson cross section [m^2], uncertainty 0.0000000062e-29 */
#define CODATA_ELECTRON_MASS_ENERGY_MEV  (0.51099895069)
    /* electron mass energy equivalent in MeV [MeV], uncertainty 0.00000000016 */
#define CODATA_FINE_STRUCTURE            (7.2973525643e-3)
    /* fine-structure constant [1], uncertainty 0.0000000011e-3 */
#define CODATA_HARTREE_ENERGY_EV         (27.211386245981)
    /* Hartree energy in eV [eV], uncertainty 0.000000000030 */

#define CODATA_EDITION 2022

#endif
