#!/usr/bin/env python3
"""Generate photoion_codataYYYY.h from NIST's CODATA table.

    python3 photoion_codata_gen.py allascii.txt

reads NIST's "Fundamental Physical Constants --- Complete Listing", as served
at https://physics.nist.gov/cuu/Constants/Table/allascii.txt (current
edition) or https://physics.nist.gov/cuu/Constants/ArchiveASCII/ (older
ones), and writes photoion_codataYYYY.h, where YYYY is the edition named in
the file. The header holds only the quantities the photoion models use, in
SI units, exactly as NIST prints them; photoion_const.h derives the cgs
values from these. Changing edition is regenerating from another table and
changing the one #include in photoion_const.h.

Only the column layout NIST has used since the 2018 edition is understood;
older tables are refused rather than misread. A value NIST truncates with
"..." (an exact constant with more digits than the table shows) is refused
too, so that nothing in the header is silently shortened.
"""
import hashlib
import re
import sys

# NIST quantity name -> (macro suffix, unit as printed by NIST)
WANTED = [
    ('speed of light in vacuum',               'SPEED_OF_LIGHT',               'm s^-1'),
    ('Planck constant',                        'PLANCK',                       'J Hz^-1'),
    ('electron volt',                          'ELECTRON_VOLT',                'J'),
    ('Bohr radius',                            'BOHR_RADIUS',                  'm'),
    ('classical electron radius',              'CLASSICAL_ELECTRON_RADIUS',    'm'),
    ('Thomson cross section',                  'THOMSON_CROSS_SECTION',        'm^2'),
    ('electron mass energy equivalent in MeV', 'ELECTRON_MASS_ENERGY_MEV',     'MeV'),
    ('fine-structure constant',                'FINE_STRUCTURE',               ''),
    ('Hartree energy in eV',                   'HARTREE_ENERGY_EV',            'eV'),
]

# Fixed column layout of NIST's table since the 2018 edition. Every field is
# validated after slicing, so a layout change fails loudly instead of being
# misread.
COLS = ((0, 60), (60, 85), (85, 110), (110, None))
NUMBER = re.compile(r'^-?[0-9][0-9 .]*?(?:\.\.\.)?(?: e[-+]?\d+)?$')


def split_row(line):
    """(name, value, uncertainty, unit), or None if not a data row."""
    if len(line) < 86 or line[59] != ' ' or line[84] != ' ':
        return None
    name, value, unc, unit = (line[a:b].strip() for a, b in COLS)
    if not name or not NUMBER.match(value):
        return None
    if unc != '(exact)' and not NUMBER.match(unc):
        return None
    return name, value, unc, unit


def main(path):
    raw = open(path, 'rb').read()
    text = raw.decode('latin-1')
    m = re.search(r'^\s*(\d{4}) CODATA adjustment', text, re.M)
    if not m:
        sys.exit('%s: no "YYYY CODATA adjustment" line; not a 2018-or-later '
                 'NIST table?' % path)
    year = m.group(1)

    rows = {}
    for line in text.splitlines():
        r = split_row(line)
        if r:
            rows[r[0]] = r
    out = []
    for name, macro, unit in WANTED:
        r = rows.get(name)
        if r is None:
            sys.exit('%s: quantity %r not found' % (path, name))
        _, value, unc, got_unit = r
        if got_unit != unit:
            sys.exit('%s: %r has unit %r, expected %r'
                     % (path, name, got_unit, unit))
        if '...' in value:
            sys.exit('%s: %r is truncated in the table (%s); refusing to '
                     'shorten it' % (path, name, value))
        value = value.replace(' ', '')
        float(value)  # must parse
        if not re.search(r'[.e]', value):
            value += '.'  # a C double, not an int: 299792458 -> 299792458.
        unc = 'exact' if unc == '(exact)' else 'uncertainty ' + unc.replace(' ', '')
        out.append((macro, value, '%s [%s], %s' % (name, unit or '1', unc)))

    guard = 'PHOTOION_CODATA%s_H' % year
    width = max(len(m) for m, _, _ in out) + len('CODATA_')
    lines = [
        '#ifndef %s' % guard,
        '#define %s' % guard,
        '',
        '/* CODATA %s recommended values, SI units, as printed by NIST.' % year,
        ' *',
        ' * GENERATED by photoion_codata_gen.py -- do not edit by hand.',
        ' * Source: NIST "Fundamental Physical Constants --- Complete Listing",',
        ' *   %s CODATA adjustment' % year,
        ' *   sha256 %s' % hashlib.sha256(raw).hexdigest(),
        ' * photoion_const.h derives the cgs values the models use from these. */',
        '',
    ]
    for macro, value, comment in out:
        lines.append('#define CODATA_%s (%s)' % (macro.ljust(width - len('CODATA_')), value))
        lines.append('    /* %s */' % comment)
    lines += ['', '#define CODATA_EDITION %s' % year, '', '#endif', '']
    dest = 'photoion_codata%s.h' % year
    open(dest, 'w').write('\n'.join(lines))
    print('wrote %s (%d constants, CODATA %s)' % (dest, len(out), year))


if __name__ == '__main__':
    if len(sys.argv) != 2:
        sys.exit(__doc__)
    main(sys.argv[1])
